export const MOVIE_FILTER_FIELD = {
    ACTORS: "actors",
    TAGS: "tags",
    DIRECTOR: "director",
    MAKER: "maker",
    SERIES: "series",
    STORAGE_STATUS: "storageStatus",
    RATING_MIN: "ratingMin",
    RATING_MAX: "ratingMax",
    ACTORS_COUNT_MIN: "actorsCountMin",
    ACTORS_COUNT_MAX: "actorsCountMax",
    RELEASE_DATE_FROM: "releaseDateFrom",
    RELEASE_DATE_TO: "releaseDateTo",
    CREATED_AT_FROM: "createdAtFrom",
    CREATED_AT_TO: "createdAtTo",
    SORT_BY: "sortBy",
} as const;

export const MOVIE_FILTER_CONFIG_ITEMS = [
    {key: "actors" as const, label: "演员筛选", defaultOrder: 0},
    {key: "actorsNot" as const, label: "排除演员", defaultOrder: 1},
    {key: "tags" as const, label: "标签筛选", defaultOrder: 2},
    {key: "tagsNot" as const, label: "排除标签", defaultOrder: 3},
    {key: "director" as const, label: "导演筛选", defaultOrder: 4},
    {key: "directorNot" as const, label: "排除导演", defaultOrder: 5},
    {key: "maker" as const, label: "片商筛选", defaultOrder: 6},
    {key: "makerNot" as const, label: "排除片商", defaultOrder: 7},
    {key: "series" as const, label: "系列筛选", defaultOrder: 8},
    {key: "seriesNot" as const, label: "排除系列", defaultOrder: 9},
    {key: "storageStatus" as const, label: "存储状态", defaultOrder: 10},
    {key: "ratingMin" as const, label: "最低评分", defaultOrder: 11},
    {key: "ratingMax" as const, label: "最高评分", defaultOrder: 12},
    {key: "actorsCountMin" as const, label: "最少演员", defaultOrder: 13},
    {key: "actorsCountMax" as const, label: "最多演员", defaultOrder: 14},
    {key: "releaseDateFrom" as const, label: "发行开始日期", defaultOrder: 15},
    {key: "releaseDateTo" as const, label: "发行结束日期", defaultOrder: 16},
    {key: "createdAtFrom" as const, label: "入库开始日期", defaultOrder: 17},
    {key: "createdAtTo" as const, label: "入库结束日期", defaultOrder: 18},
    {key: "sortBy" as const, label: "排序", defaultOrder: 19},
];
